# Generated by Django 5.1.13 on 2025-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_deportivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(through='eventos_deportivos.EquipoJugador', to='eventos_deportivos.jugador'),
        ),
    ]
