# Generated by Django 5.1.13 on 2025-10-22 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_deportivos', '0002_equipo_jugadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='estadio_principal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneo_dirigido', to='eventos_deportivos.estadio'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='arbitro_principal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='torneo_dirigido', to='eventos_deportivos.arbitro'),
        ),
    ]
