# Generated by Django 5.1.13 on 2025-12-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_deportivos', '0003_equipo_estadio_principal_torneo_arbitro_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eventos_deportivos/estadios/'),
        ),
    ]
